/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AttestedSignature from '../../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.bids.x402'

export { $nsid }

/** Includes pricing/payment terms and x402 endpoint for issuing a receipt against an accept. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.bids.x402'

  /**
   * Numeric price (integer or float) per the chosen frequency.
   */
  cost: l.LexMap

  /**
   * Currency code, e.g. 'USDC'.
   */
  currency: string

  /**
   * Billing frequency, e.g. 'monthly', 'hourly', 'one-time'.
   */
  frequency: string

  /**
   * Whether payment is required before compute starts.
   */
  prepay: boolean

  /**
   * x402 payment endpoint URL. To settle payment the requester first mints a com.publicdomainrelay.temp.market.accepts.x402 record, then issues an x402-gated GET to `{url}/{accepts.x402 AT-URI}/{accepts.x402 CID}`; on payment the bidder mints and returns a com.publicdomainrelay.temp.market.receipts.x402 proof-of-payment record. That receipt is then used as the payload of the higher-level com.publicdomainrelay.temp.market.accept.
   */
  url: string

  /**
   * badge.blue attestations over these payment terms. Must include the bidder's inline signature, attached at creation, so the advertised price and payment endpoint are non-repudiable.
   */
  signatures: AttestedSignature.Signatures
}

export type { Main }

/** Includes pricing/payment terms and x402 endpoint for issuing a receipt against an accept. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    cost: /*#__PURE__*/ l.lexMap(),
    currency: /*#__PURE__*/ l.string(),
    frequency: /*#__PURE__*/ l.string(),
    prepay: /*#__PURE__*/ l.boolean(),
    url: /*#__PURE__*/ l.string(),
    signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
      (() => AttestedSignature.signatures) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
