/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../../atproto/repo/strongRef.defs.ts'
import * as AttestedSignature from '../../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.accepts.free'

export { $nsid }

/** The requester's acceptance of a bid's free (no-cost) terms. Minted before settling and passed (by AT-URI + CID) to the grant endpoint named in the bids.free url; the bidder resolves it and mints a com.publicdomainrelay.temp.market.receipts.free in response. The free counterpart of com.publicdomainrelay.temp.market.accepts.x402. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.accepts.free'

  /**
   * Strong reference to the winning bid record (com.publicdomainrelay.temp.market.bid) whose bids.free terms are being accepted.
   */
  bid: RepoStrongRef.Main

  /**
   * Strong reference to the bid's terms record being accepted (for example a com.publicdomainrelay.temp.market.bids.free).
   */
  payload?: RepoStrongRef.Main

  /**
   * badge.blue attestations over this acceptance. Must include the requester's inline signature, attached at creation; the bidder's receipts.free remote attestation completes the bilateral agreement.
   */
  signatures: AttestedSignature.Signatures
}

export type { Main }

/** The requester's acceptance of a bid's free (no-cost) terms. Minted before settling and passed (by AT-URI + CID) to the grant endpoint named in the bids.free url; the bidder resolves it and mints a com.publicdomainrelay.temp.market.receipts.free in response. The free counterpart of com.publicdomainrelay.temp.market.accepts.x402. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    bid: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    payload: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
      (() => AttestedSignature.signatures) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
