/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.ts'
import * as AttestedSignature from './signature.defs.ts'

const $nsid = 'network.attested.proof'

export { $nsid }

/** A remote attestation proof: a standalone record in the attestor's repository that binds, via a canonical attestation CID, to a subject record living elsewhere. Referenced from the subject's `signatures` array via com.atproto.repo.strongRef. The `cid` is computed from the subject record (signatures stripped) with this record's metadata (cid/signature/signatures stripped, `repository` = subject's repo DID added) inserted as $sig, DAG-CBOR + SHA-256 + CIDv1. Verifiers recompute that CID and require it to match; copying the subject to another repository changes the CID and invalidates the proof. The shared network.attested.* replacement for app-specific remote-attestation records. */
type Main = {
  $type: 'network.attested.proof'

  /**
   * Strong reference to the record being attested, so verifiers can fetch it and recompute the attestation CID.
   */
  subject: RepoStrongRef.Main

  /**
   * Canonical attestation CID computed over the subject record, this record's metadata, and the subject's repository DID.
   */
  cid: l.CidString

  /**
   * DID of the attesting party (e.g. the did:web of the service that minted this proof).
   */
  issuer?: l.DidString

  /**
   * The role this proof attests in a workflow (e.g. 'proof-of-settlement', 'broker', 'verification'), so verifiers can require specific attestation completeness.
   */
  role?: string

  /**
   * Optional status of the attested subject (e.g. 'valid', 'revoked').
   */
  status?: string
  createdAt: l.DatetimeString

  /**
   * Attestations over this proof record itself (the attestor's inline signature).
   */
  signatures?: AttestedSignature.Signatures
}

export type { Main }

/** A remote attestation proof: a standalone record in the attestor's repository that binds, via a canonical attestation CID, to a subject record living elsewhere. Referenced from the subject's `signatures` array via com.atproto.repo.strongRef. The `cid` is computed from the subject record (signatures stripped) with this record's metadata (cid/signature/signatures stripped, `repository` = subject's repo DID added) inserted as $sig, DAG-CBOR + SHA-256 + CIDv1. Verifiers recompute that CID and require it to match; copying the subject to another repository changes the CID and invalidates the proof. The shared network.attested.* replacement for app-specific remote-attestation records. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    subject: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    cid: /*#__PURE__*/ l.string({ format: 'cid' }),
    issuer: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'did' })),
    role: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    status: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    signatures: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
        (() => AttestedSignature.signatures) as any,
      ),
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
