/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AttestedSignature from './signature.defs.ts'

const $nsid = 'network.attested.verify'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  uri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  uri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
  cid: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'cid' })),
  valid: /*#__PURE__*/ l.boolean(),
  signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
    (() => AttestedSignature.signatures) as any,
  ),
  workflow: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Verify the attestations on a record. Resolves the record at `uri`, recomputes the canonical attestation CID, and checks each entry in its signatures array: inline network.attested.signature entries are verified by ECDSA against `key`; remote strongRefs are resolved to network.attested.proof records whose `cid` must match the subject's canonical CID. Any network.attested.* speaker can call this to verify without re-deriving the CID machinery. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid
