/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.compute.vm'

export { $nsid }

/** Descibes a virtual machine */
type Main = {
  $type: 'com.publicdomainrelay.temp.compute.vm'

  /**
   * Number of vCPUs requested.
   */
  cpus: number

  /**
   * Memory request, e.g. '512M', '4G'.
   */
  mem: string

  /**
   * Disk request, e.g. '10G'.
   */
  disk: string

  /**
   * Network throughput / quota, e.g. '500G'.
   */
  network: string
  location?: Location

  /**
   * RBAC role the compute should run under. The requester's did:plc may set this freely, so agents must use their own accounts since we scope roles under accounts.
   */
  role: string

  /**
   * cloud-init user data to bootstrap the compute.
   */
  user_data: string
}

export type { Main }

/** Descibes a virtual machine */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    cpus: /*#__PURE__*/ l.integer({ minimum: 1 }),
    mem: /*#__PURE__*/ l.string(),
    disk: /*#__PURE__*/ l.string(),
    network: /*#__PURE__*/ l.string(),
    location: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Location>((() => location) as any),
    ),
    role: /*#__PURE__*/ l.string(),
    user_data: /*#__PURE__*/ l.string(),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Geographic placement constraint for the requested compute. */
type Location = {
  $type?: 'com.publicdomainrelay.temp.compute.vm#location'

  /**
   * ISO 3166-1 alpha-3 country code or human-readable country name.
   */
  country?: string

  /**
   * Region within the country, e.g. 'west'.
   */
  region?: string
}

export type { Location }

/** Geographic placement constraint for the requested compute. */
const location = /*#__PURE__*/ l.typedObject<Location>(
  $nsid,
  'location',
  /*#__PURE__*/ l.object({
    country: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    region: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  }),
)

export { location }
