/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.compute.events.vm.delete'

export { $nsid }

/** Requests that the provider delete/tear down a provisioned VM — e.g. because its workflow finished, or because its policy engine never came up. Sent by the requester, since the provider treats the VM as a black box and cannot observe these conditions itself. */
type Main = {
  $type: 'com.publicdomainrelay.temp.compute.events.vm.delete'

  /**
   * Why the VM should be deleted, e.g. 'workflow_complete' or 'policy_engine_never_came_up'.
   */
  reason: string
  createdAt: l.DatetimeString
}

export type { Main }

/** Requests that the provider delete/tear down a provisioned VM — e.g. because its workflow finished, or because its policy engine never came up. Sent by the requester, since the provider treats the VM as a black box and cannot observe these conditions itself. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    reason: /*#__PURE__*/ l.string(),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
