/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../../atproto/repo/strongRef.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.receipts.free'

export { $nsid }

/** Proof-of-grant receipt minted by the bidder in response to a GET against the bids.free url. No payment is involved; the receipt is the bidder's verifiable record that it agreed to provide the resource for free. Returned (by AT-URI + CID) to the requester, which uses it as the payload of the higher-level com.publicdomainrelay.temp.market.accept so the bidder can verify the grant before provisioning. The free counterpart of com.publicdomainrelay.temp.market.receipts.x402. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.receipts.free'

  /**
   * Strong reference to the com.publicdomainrelay.temp.market.accepts.free record that this grant settles.
   */
  accept: RepoStrongRef.Main
}

export type { Main }

/** Proof-of-grant receipt minted by the bidder in response to a GET against the bids.free url. No payment is involved; the receipt is the bidder's verifiable record that it agreed to provide the resource for free. Returned (by AT-URI + CID) to the requester, which uses it as the payload of the higher-level com.publicdomainrelay.temp.market.accept so the bidder can verify the grant before provisioning. The free counterpart of com.publicdomainrelay.temp.market.receipts.x402. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    accept: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
