/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.agent.class'

export { $nsid }

/** An agent class definition. Acts as a template that agents are instantiated from. The class is a named bundle of skills (strongRefs to com.publicdomainrelay.temp.agent.skill records) plus optional metadata. Instantiating an agent from a class means spawning a runtime (or sub-agent context) seeded with this skill set. */
type Main = {
  $type: 'com.publicdomainrelay.temp.agent.class'

  /**
   * Human-readable name of the agent class, e.g. 'compute-requester'.
   */
  name: string

  /**
   * Description of what agents instantiated from this class are for and what they can do.
   */
  description: string

  /**
   * Strong references to com.publicdomainrelay.temp.agent.skill records that compose this class.
   */
  skills: RepoStrongRef.Main[]

  /**
   * Optional strongRef to a parent agent.class. Instantiated agents inherit the parent's skills as well as this class's skills.
   */
  parent?: RepoStrongRef.Main

  /**
   * If true, agents of this class are intended to be spawned as sub-agents from a parent agent's flow rather than as a top-level runtime.
   */
  spawnsSubAgent?: boolean

  /**
   * ISO 8601 timestamp when this class record was created.
   */
  createdAt: l.DatetimeString
}

export type { Main }

/** An agent class definition. Acts as a template that agents are instantiated from. The class is a named bundle of skills (strongRefs to com.publicdomainrelay.temp.agent.skill records) plus optional metadata. Instantiating an agent from a class means spawning a runtime (or sub-agent context) seeded with this skill set. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.string(),
    description: /*#__PURE__*/ l.string(),
    skills: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    parent: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    spawnsSubAgent: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
