/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.agent.skill'

export { $nsid }

/** An agent skill record that describes a capability the agent can perform, with examples and property references. */
type Main = {
  $type: 'com.publicdomainrelay.temp.agent.skill'

  /**
   * Human-readable name of the skill.
   */
  name: string

  /**
   * Instructions for when and how to use this skill.
   */
  description: string

  /**
   * The skill itself.
   */
  content: string

  /**
   * Strong references to example records demonstrating this skill.
   */
  examples?: RepoStrongRef.Main[]

  /**
   * Annotated path-value pairs describing fields within the example records. Each entry either carries a literal string value or a strongRef that resolves (recursively) to the value at that path.
   */
  property_references?: PropertyReference[]

  /**
   * ISO 8601 timestamp when this skill record was created.
   */
  createdAt: string
}

export type { Main }

/** An agent skill record that describes a capability the agent can perform, with examples and property references. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.string(),
    description: /*#__PURE__*/ l.string(),
    content: /*#__PURE__*/ l.string(),
    examples: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
          (() => RepoStrongRef.main) as any,
        ),
      ),
    ),
    property_references: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<PropertyReference>(
          (() => propertyReference) as any,
        ),
      ),
    ),
    createdAt: /*#__PURE__*/ l.string(),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** A single path-annotated value reference within a skill's example records. Carries either a literal string or a strongRef pointing to the value. */
type PropertyReference = {
  $type?: 'com.publicdomainrelay.temp.agent.skill#propertyReference'

  /**
   * JSONPath-like dotted path into the resolved example tree, e.g. '.examples[].value.payload.value.user_data'.
   */
  path: string

  /**
   * Strong reference to a record that contains the example data.
   */
  ref?: RepoStrongRef.Main
}

export type { PropertyReference }

/** A single path-annotated value reference within a skill's example records. Carries either a literal string or a strongRef pointing to the value. */
const propertyReference = /*#__PURE__*/ l.typedObject<PropertyReference>(
  $nsid,
  'propertyReference',
  /*#__PURE__*/ l.object({
    path: /*#__PURE__*/ l.string(),
    ref: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
  }),
)

export { propertyReference }
