/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.ts'
import * as AttestedSignature from '../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.accept'

export { $nsid }

/** Acceptance of a bid on an RFP */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.accept'

  /**
   * Strong reference to the rfp record (for example a com.publicdomainrelay.temp.market.rfp).
   */
  rfp: RepoStrongRef.Main

  /**
   * Strong reference to the bid record (for example a com.publicdomainrelay.temp.market.bid.x402).
   */
  bid: RepoStrongRef.Main

  /**
   * Strong reference to the proof-of-payment record returned by the bid's payment flow (for example a com.publicdomainrelay.temp.market.receipts.x402 obtained from the x402 GET against the bids.x402 url). The bidder verifies this before provisioning.
   */
  payload?: RepoStrongRef.Main

  /**
   * Service DID reference (did:web:HOST#compute_event) of the RFP issuer's compute-event service. Optional; bypasses the need for events to be seen in the firehose. The counterparty calls com.publicdomainrelay.temp.market.submitEvent via PDS service-proxying using this value as the atproto-proxy target.
   */
  submitEvent?: string

  /**
   * badge.blue attestations over this accept. Must include the requester's inline signature, attached at creation. The bidder's side of the bilateral agreement is its proof-of-settlement record (the accept's payload) and the market.receipt it mints on submitAccept, both of which are badge.blue remote attestations bound to this record.
   */
  signatures: AttestedSignature.Signatures
}

export type { Main }

/** Acceptance of a bid on an RFP */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    rfp: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    bid: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    payload: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    submitEvent: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
      (() => AttestedSignature.signatures) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
