/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.attestation'

export { $nsid }

/** badge.blue remote attestation proof record (https://badge.blue). Stored in the attestor's repository and referenced from the subject record's signatures array via com.atproto.repo.strongRef. The `cid` is the badge.blue attestation CID: the subject record (signatures stripped) with this record's metadata (cid/signature/signatures stripped, `repository` = subject's repo DID added) inserted as $sig, serialized to DAG-CBOR, SHA-256 hashed, wrapped as CIDv1 (dag-cbor codec). Verifiers recompute that CID and require it to match; copying the subject record to another repository changes the CID and invalidates the proof. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.attestation'

  /**
   * Strong reference to the record being attested, so verifiers can fetch it and recompute the attestation CID.
   */
  subject: RepoStrongRef.Main

  /**
   * badge.blue attestation CID computed over the subject record, this record's metadata, and the subject's repository DID.
   */
  cid: l.CidString

  /**
   * DID of the attesting party (e.g. the did:web of the service that minted this proof).
   */
  issuer?: l.DidString

  /**
   * What this attestation asserts, e.g. 'verification', 'approval', 'endorsement'.
   */
  purpose?: string
  createdAt: l.DatetimeString

  /**
   * badge.blue attestations over this proof record itself (the attestor's inline signature).
   */
  signatures?: Signatures
}

export type { Main }

/** badge.blue remote attestation proof record (https://badge.blue). Stored in the attestor's repository and referenced from the subject record's signatures array via com.atproto.repo.strongRef. The `cid` is the badge.blue attestation CID: the subject record (signatures stripped) with this record's metadata (cid/signature/signatures stripped, `repository` = subject's repo DID added) inserted as $sig, serialized to DAG-CBOR, SHA-256 hashed, wrapped as CIDv1 (dag-cbor codec). Verifiers recompute that CID and require it to match; copying the subject record to another repository changes the CID and invalidates the proof. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    subject: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    cid: /*#__PURE__*/ l.string({ format: 'cid' }),
    issuer: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'did' })),
    purpose: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    signatures: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<Signatures>((() => signatures) as any),
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** badge.blue inline attestation: an ECDSA signature over the attestation CID, embedded in the record's signatures array. The CID is computed from the record (signatures stripped), this entry's metadata (cid/signature stripped, `repository` = authoring repo DID added) inserted as $sig, DAG-CBOR + SHA-256 + CIDv1. Signatures are low-S normalized; supported curves are P-256 and K-256 (did:key). */
type Inline = {
  $type?: 'com.publicdomainrelay.temp.market.attestation#inline'

  /**
   * did:key public-key reference used to verify the signature.
   */
  key: string

  /**
   * DID of the signing party (e.g. the did:web of the service holding the key). Verifiers may bind `key` to this DID's document when the authoring account's DID document does not list it.
   */
  issuer?: l.DidString
  issuedAt?: l.DatetimeString

  /**
   * The computed badge.blue attestation CID (base32 CIDv1) this entry signs.
   */
  cid: l.CidString

  /**
   * Low-S normalized ECDSA signature over the CID bytes.
   */
  signature: Uint8Array
}

export type { Inline }

/** badge.blue inline attestation: an ECDSA signature over the attestation CID, embedded in the record's signatures array. The CID is computed from the record (signatures stripped), this entry's metadata (cid/signature stripped, `repository` = authoring repo DID added) inserted as $sig, DAG-CBOR + SHA-256 + CIDv1. Signatures are low-S normalized; supported curves are P-256 and K-256 (did:key). */
const inline = /*#__PURE__*/ l.typedObject<Inline>(
  $nsid,
  'inline',
  /*#__PURE__*/ l.object({
    key: /*#__PURE__*/ l.string(),
    issuer: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'did' })),
    issuedAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
    cid: /*#__PURE__*/ l.string({ format: 'cid' }),
    signature: /*#__PURE__*/ l.bytes(),
  }),
)

export { inline }

/** badge.blue signatures array: inline attestations and/or strongRefs to remote attestation proof records (com.publicdomainrelay.temp.market.attestation). Always stripped from the record before attestation-CID computation, so attaching attestations never changes the signing payload. */
type Signatures = (
  | l.$Typed<Inline>
  | l.$Typed<RepoStrongRef.Main>
  | l.Unknown$TypedObject
)[]

export type { Signatures }

/** badge.blue signatures array: inline attestations and/or strongRefs to remote attestation proof records (com.publicdomainrelay.temp.market.attestation). Always stripped from the record before attestation-CID computation, so attaching attestations never changes the signing payload. */
const signatures = /*#__PURE__*/ l.array<Signatures[number]>(
  /*#__PURE__*/ l.typedUnion(
    [
      /*#__PURE__*/ l.typedRef<Inline>((() => inline) as any),
      /*#__PURE__*/ l.typedRef<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ],
    false,
  ),
)

export { signatures }
