/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.market.badgeBlueKey'

export { $nsid }

/** Publishes the public half of a badge.blue attestation key that this repo signs market.* records with. The record key is the key's did:key, so a verifier can look up a key by did:key directly in the author's PDS repo — a PDS-native key registry complementing DID-document key binding. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.badgeBlueKey'

  /**
   * The did:key of the public key (the same value as this record's key).
   */
  key: l.DidString

  /**
   * DID (e.g. a did:web) that controls/advertises this key when it is bound to a service identity.
   */
  issuer?: l.DidString
  createdAt: l.DatetimeString
}

export type { Main }

/** Publishes the public half of a badge.blue attestation key that this repo signs market.* records with. The record key is the key's did:key, so a verifier can look up a key by did:key directly in the author's PDS repo — a PDS-native key registry complementing DID-document key binding. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    key: /*#__PURE__*/ l.string({ format: 'did' }),
    issuer: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'did' })),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
