/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.ts'
import * as AttestedSignature from '../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.bid'

export { $nsid }

/** A bid on an RFP */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.bid'

  /**
   * Strong reference to the rfp record (for example a com.publicdomainrelay.temp.market.rfp).
   */
  rfp: RepoStrongRef.Main

  /**
   * Strong reference to any config information that needs to be processed by rfp actor prior to bid accept (for example a com.publicdomainrelay.temp.compute.config.wif.simple).
   */
  config?: RepoStrongRef.Main

  /**
   * Strong reference to the bid record (for example a com.publicdomainrelay.temp.market.bids.x402).
   */
  payload: RepoStrongRef.Main

  /**
   * Service DID reference (did:web:HOST#temp_market) of the bidder's market service. Once the requester has settled payment (via the x402 flow named in the bids.x402 payload) and minted a com.publicdomainrelay.temp.market.accept, it calls com.publicdomainrelay.temp.market.submitAccept via PDS service-proxying using this value as the atproto-proxy target to provision the resource and obtain a com.publicdomainrelay.temp.market.receipt.
   */
  submitAccept?: string

  /**
   * badge.blue attestations over this bid. Must include the bidder's inline signature, attached at creation (before any accept strongRefs this record); post-hoc third-party attestations use remote network.attested.signature proof records instead, so the bid's CID stays stable.
   */
  signatures: AttestedSignature.Signatures
}

export type { Main }

/** A bid on an RFP */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    rfp: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    config: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    payload: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    submitAccept: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
      (() => AttestedSignature.signatures) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
