/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.ts'
import * as AttestedSignature from '../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.event'

export { $nsid }

/** A lifecycle event reported against a receipt (e.g. a provider-opaque resource like a VM coming up, joining the network, or needing to be deleted). */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.event'

  /**
   * Strong reference to the receipt record this event pertains to (for example a com.publicdomainrelay.temp.market.receipt), so the counterparty can map the event back to the resource it provisioned.
   */
  receipt: RepoStrongRef.Main

  /**
   * Strong reference to the domain-specific event payload record (for example a com.publicdomainrelay.temp.compute.events.vm.started, .onNetwork, or .delete).
   */
  payload: RepoStrongRef.Main

  /**
   * badge.blue attestations over this event. Must include the reporting party's inline signature, attached at creation, making the lifecycle claim non-repudiable — events assert facts about resources the counterparty cannot observe itself.
   */
  signatures: AttestedSignature.Signatures
}

export type { Main }

/** A lifecycle event reported against a receipt (e.g. a provider-opaque resource like a VM coming up, joining the network, or needing to be deleted). */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    receipt: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    payload: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
      (() => AttestedSignature.signatures) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
