/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.market.offering'

export { $nsid }

/** Declares that a bidder is willing to submit bids for RFPs whose payload NSID is in appliesTo. The bidder's market service DID reference (for submitRfp via PDS proxying) is given by endpointUrl. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.offering'

  /**
   * Service DID reference (did:web:HOST#temp_market) of the bidder's market service. RFP issuers call com.publicdomainrelay.temp.market.submitRfp via PDS service-proxying using this value as the atproto-proxy target.
   */
  endpointUrl: string

  /**
   * List of payload NSIDs this bidder handles (e.g. com.publicdomainrelay.temp.compute.vm).
   */
  appliesTo: l.NsidString[]
  createdAt: l.DatetimeString
}

export type { Main }

/** Declares that a bidder is willing to submit bids for RFPs whose payload NSID is in appliesTo. The bidder's market service DID reference (for submitRfp via PDS proxying) is given by endpointUrl. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    endpointUrl: /*#__PURE__*/ l.string(),
    appliesTo: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.string({ format: 'nsid' }),
      { minLength: 1 },
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
