/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.ts'
import * as AttestedSignature from '../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.receipt'

export { $nsid }

/** Receipt for acceptance of a bid on an RFP */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.receipt'

  /**
   * Strong reference to the rfp record (for example a com.publicdomainrelay.temp.market.rfp).
   */
  rfp: RepoStrongRef.Main

  /**
   * Strong reference to the bid record (for example a com.publicdomainrelay.temp.market.bid.x402).
   */
  bid: RepoStrongRef.Main

  /**
   * Strong reference to the accept record (for example a com.publicdomainrelay.temp.market.accept.x402).
   */
  accept: RepoStrongRef.Main

  /**
   * Strong reference to the receipt record if there is anything to note about the receipt (for example a com.publicdomainrelay.temp.market.receipt.x402).
   */
  payload?: RepoStrongRef.Main

  /**
   * Service DID reference (did:web:HOST#compute_event) of the provider's compute-event service, scoped to this receipt's strongRef. The requester calls com.publicdomainrelay.temp.market.submitEvent via PDS service-proxying using this value as the atproto-proxy target, to report lifecycle events the provider cannot observe itself (e.g. compute.events.vm.delete when a workflow finishes or its policy engine never comes up), since the provider treats provisioned resources as a black box.
   */
  submitEvent?: string

  /**
   * badge.blue attestation CID over the referenced accept record, making this receipt a remote attestation proof: computed from the accept record (signatures stripped), this receipt's metadata (cid/signatures stripped, repository = accept's repo DID added) as $sig, via DAG-CBOR + SHA-256 + CIDv1. Binds the receipt to the accept's exact content in the requester's repository.
   */
  cid: l.CidString

  /**
   * badge.blue attestations over this receipt. Must include the provider's inline signature, attached at creation.
   */
  signatures: AttestedSignature.Signatures
}

export type { Main }

/** Receipt for acceptance of a bid on an RFP */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    rfp: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    bid: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    accept: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    payload: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
        (() => RepoStrongRef.main) as any,
      ),
    ),
    submitEvent: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    cid: /*#__PURE__*/ l.string({ format: 'cid' }),
    signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
      (() => AttestedSignature.signatures) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
