/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.ts'
import * as AttestedSignature from '../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.rfp'

export { $nsid }

/** Top-level Request For Proposal (RFP). Envelope that strongRefs a domain-specific payload (e.g. compute.vm). */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.rfp'

  /**
   * Strong reference to the domain-specific payload record (for example a com.publicdomainrelay.temp.compute.vm).
   */
  payload: RepoStrongRef.Main

  /**
   * Service DID reference (did:web:HOST#temp_market) of the RFP issuer's market service. Optional; bypasses the need for bids to be seen in the firehose. The bidder calls com.publicdomainrelay.temp.market.submitBid via PDS service-proxying using this value as the atproto-proxy target.
   */
  submitBid?: string

  /**
   * badge.blue attestations over this RFP. Must include the issuer's inline signature, attached at creation (before any bid strongRefs this record); post-hoc third-party attestations use remote network.attested.signature proof records instead, so the RFP's CID stays stable.
   */
  signatures: AttestedSignature.Signatures
}

export type { Main }

/** Top-level Request For Proposal (RFP). Envelope that strongRefs a domain-specific payload (e.g. compute.vm). */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    payload: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    submitBid: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
      (() => AttestedSignature.signatures) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
