/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as MarketEvent from './event.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.submitEvent'

export { $nsid }

export const $params = /*#__PURE__*/ l.params()

export type $Params = l.InferOutput<typeof $params>

export const $input = /*#__PURE__*/ l.jsonPayload({
  uri: /*#__PURE__*/ l.string(),
  cid: /*#__PURE__*/ l.string(),
  record: /*#__PURE__*/ l.ref<MarketEvent.Main>(
    (() => MarketEvent.main) as any,
  ),
})

export type $Input<B = l.BinaryData> = l.InferPayload<typeof $input, B>
export type $InputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $input, B>

export const $output = /*#__PURE__*/ l.jsonPayload({
  ok: /*#__PURE__*/ l.boolean(),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Submit the AT-URI and CID of an event record directly to the counterparty, bypassing the firehose. Used when the accept or receipt includes a submitEvent service DID reference — e.g. so a requester can tell a bidder to delete a VM whose workflow finished, or whose policy engine never came up, since the bidder treats the VM as a black box. Must be called via PDS service-proxying (atproto-proxy); the receiver verifies the inter-service auth JWT and requires its issuer to be the DID that authored the referenced event record. The receiver additionally verifies the event's badge.blue attestations (network.attested.signature): at least one inline signature must verify against the attestation CID recomputed for the record in its authoring repository, making lifecycle claims about provider-opaque resources non-repudiable. */
const main = /*#__PURE__*/ l.procedure($nsid, $params, $input, $output, [
  'InvalidRequest',
])

export { main }

export const $lxm = $nsid
