/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as MarketBid from './bid.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.submitBid'

export { $nsid }

export const $params = /*#__PURE__*/ l.params()

export type $Params = l.InferOutput<typeof $params>

export const $input = /*#__PURE__*/ l.jsonPayload({
  uri: /*#__PURE__*/ l.string(),
  cid: /*#__PURE__*/ l.string(),
  record: /*#__PURE__*/ l.ref<MarketBid.Main>((() => MarketBid.main) as any),
})

export type $Input<B = l.BinaryData> = l.InferPayload<typeof $input, B>
export type $InputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $input, B>

export const $output = /*#__PURE__*/ l.jsonPayload({
  ok: /*#__PURE__*/ l.boolean(),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Submit the AT-URI and CID of a bid record directly to the RFP issuer, bypassing the firehose. Used when the RFP includes a submitBid service DID reference. Must be called via PDS service-proxying (atproto-proxy); the receiver verifies the inter-service auth JWT and requires its issuer to be the DID that authored the referenced bid record. The receiver additionally verifies the bid's badge.blue attestations (network.attested.signature): at least one inline signature must verify against the attestation CID recomputed for the record in its authoring repository — the same durable, replayable check applied to bids discovered via the firehose, where no service-auth JWT exists. */
const main = /*#__PURE__*/ l.procedure($nsid, $params, $input, $output, [
  'InvalidRequest',
])

export { main }

export const $lxm = $nsid
