/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.compute.config.wif.simple'

export { $nsid }

/** Simple Workload Identity Federation parameters used by the requester to obtain a token authorized for the provider. */
type Main = {
  $type: 'com.publicdomainrelay.temp.compute.config.wif.simple'

  /**
   * Path on disk to the
   */
  accept_path: string

  /**
   * OIDC issuer URI, rfp actor configures their RBAC to trust this
   */
  issuer_uri: string

  /**
   * The role of the token you will be issued within this compute providers RBAC, this role will allow for token exchange. You don't care about it unless you might be allowed to do other things. Inspect their RBAC policy if you care.
   */
  to_issue: string

  /**
   * Path to file containing a string representing the auth context which might need to be formatted into the subject
   */
  actx_path?: string

  /**
   * Workload identity token which can be used with token issuance service for requesting subsequent tokens to talk to other services.
   */
  token_path: string

  /**
   * Path on disk to file containing URL of token issuance service for requesting subsequent tokens from.
   */
  url_path: string

  /**
   * The route against $(cat url_path) you can request new tokens from.
   */
  url_route: string

  /**
   * The subject of tokens you request MUST follow this format.
   */
  subject: string
}

export type { Main }

/** Simple Workload Identity Federation parameters used by the requester to obtain a token authorized for the provider. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    accept_path: /*#__PURE__*/ l.string(),
    issuer_uri: /*#__PURE__*/ l.string(),
    to_issue: /*#__PURE__*/ l.string(),
    actx_path: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    token_path: /*#__PURE__*/ l.string(),
    url_path: /*#__PURE__*/ l.string(),
    url_route: /*#__PURE__*/ l.string(),
    subject: /*#__PURE__*/ l.string(),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
