/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AttestedSignature from '../../../../network/attested/signature.defs.ts'

const $nsid = 'com.fedproxy.temp.xrpc.registration'

export { $nsid }

/** A subscriber's signed registration. Proves custody of the did:key by carrying badge.blue attestations (network.attested.signature) over the nonce returned from com.fedproxy.temp.xrpc.getRegistrationNonce. Presented as the parameter to com.fedproxy.temp.xrpc.subscribe to open a relay channel bound to this key. */
type Main = {
  $type: 'com.fedproxy.temp.xrpc.registration'

  /**
   * did:key public-key reference that signed the nonce; must match the key passed to getRegistrationNonce.
   */
  key: string

  /**
   * The 64-byte nonce issued by com.fedproxy.temp.xrpc.getRegistrationNonce that this registration signs over.
   */
  nonce: Uint8Array

  /**
   * badge.blue attestations (network.attested.signature) over the issued nonce, proving liveness and custody of the did:key.
   */
  signatures: AttestedSignature.Signatures
}

export type { Main }

/** A subscriber's signed registration. Proves custody of the did:key by carrying badge.blue attestations (network.attested.signature) over the nonce returned from com.fedproxy.temp.xrpc.getRegistrationNonce. Presented as the parameter to com.fedproxy.temp.xrpc.subscribe to open a relay channel bound to this key. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    key: /*#__PURE__*/ l.string(),
    nonce: /*#__PURE__*/ l.bytes(),
    signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
      (() => AttestedSignature.signatures) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
