/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.fedproxy.temp.xrpc.subscribe'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  registration: /*#__PURE__*/ l.string(),
})

export type $Params = l.InferOutput<typeof $params>

export const $message = /*#__PURE__*/ l.typedUnion(
  [
    /*#__PURE__*/ l.typedRef<Registered>((() => registered) as any),
    /*#__PURE__*/ l.typedRef<Request>((() => request) as any),
    /*#__PURE__*/ l.typedRef<Response>((() => response) as any),
  ],
  false,
)

export type $Message = l.InferOutput<typeof $message>

/** Open a relay channel. The subscriber presents a com.fedproxy.temp.xrpc.registration: a record signed (network.attested.signature) over the nonce previously issued by com.fedproxy.temp.xrpc.getRegistrationNonce. The relay verifies the registration's signatures against the issued nonce and the did:key, then binds the WebSocket to that key. On connect the relay sends a #registered frame with the assigned serviceId/proxyRef; subsequent #request frames carry inbound XRPC calls the subscriber answers with #response frames. */
const main = /*#__PURE__*/ l.subscription($nsid, $params, $message, [
  'InvalidRequest',
  'Unauthorized',
])

export { main }

export const $lxm = $nsid

/** First frame sent by the relay on connect, assigning this subscriber a serviceId. */
type Registered = {
  $type?: 'com.fedproxy.temp.xrpc.subscribe#registered'

  /**
   * Opaque id the relay assigns to this subscriber for the connection lifetime.
   */
  serviceId: string

  /**
   * did:web:HOST#serviceId value callers pass as the atproto-proxy header to route XRPC calls to this subscriber.
   */
  proxyRef: string
}

export type { Registered }

/** First frame sent by the relay on connect, assigning this subscriber a serviceId. */
const registered = /*#__PURE__*/ l.typedObject<Registered>(
  $nsid,
  'registered',
  /*#__PURE__*/ l.object({
    serviceId: /*#__PURE__*/ l.string(),
    proxyRef: /*#__PURE__*/ l.string(),
  }),
)

export { registered }

/** An inbound XRPC call relayed to the subscriber to handle. */
type Request = {
  $type?: 'com.fedproxy.temp.xrpc.subscribe#request'
  requestId: string
  method: string
  nsid: l.NsidString

  /**
   * Query params as a map of string keys to string values.
   */
  params: l.LexMap
  body?: l.LexMap
  callerDid: l.DidString
}

export type { Request }

/** An inbound XRPC call relayed to the subscriber to handle. */
const request = /*#__PURE__*/ l.typedObject<Request>(
  $nsid,
  'request',
  /*#__PURE__*/ l.object({
    requestId: /*#__PURE__*/ l.string(),
    method: /*#__PURE__*/ l.string(),
    nsid: /*#__PURE__*/ l.string({ format: 'nsid' }),
    params: /*#__PURE__*/ l.lexMap(),
    body: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
    callerDid: /*#__PURE__*/ l.string({ format: 'did' }),
  }),
)

export { request }

/** The subscriber's reply to a #request, keyed by the same requestId. */
type Response = {
  $type?: 'com.fedproxy.temp.xrpc.subscribe#response'
  requestId: string
  status: number
  body?: l.LexMap
  contentType?: string
}

export type { Response }

/** The subscriber's reply to a #request, keyed by the same requestId. */
const response = /*#__PURE__*/ l.typedObject<Response>(
  $nsid,
  'response',
  /*#__PURE__*/ l.object({
    requestId: /*#__PURE__*/ l.string(),
    status: /*#__PURE__*/ l.integer(),
    body: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
    contentType: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  }),
)

export { response }
