/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.tangled.spindle.trigger'

export { $nsid }

export const $params = /*#__PURE__*/ l.params()

export type $Params = l.InferOutput<typeof $params>

export const $input = /*#__PURE__*/ l.jsonPayload({
  knot: /*#__PURE__*/ l.string(),
  pipelineRkey: /*#__PURE__*/ l.string(),
  actor: /*#__PURE__*/ l.string({ format: 'did' }),
  repoDid: /*#__PURE__*/ l.string({ format: 'did' }),
  repoName: /*#__PURE__*/ l.string(),
  ref: /*#__PURE__*/ l.string(),
  inputs: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
})

export type $Input<B = l.BinaryData> = l.InferPayload<typeof $input, B>
export type $InputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $input, B>

export const $output = /*#__PURE__*/ l.jsonPayload({
  submitted: /*#__PURE__*/ l.boolean(),
  knot: /*#__PURE__*/ l.string(),
  pipelineRkey: /*#__PURE__*/ l.string(),
  ref: /*#__PURE__*/ l.string(),
  workflows: /*#__PURE__*/ l.array(
    /*#__PURE__*/ l.ref<WorkflowResult>((() => workflowResult) as any),
  ),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Manually trigger a pipeline run on a Tangled spindle. Intended to be called via PDS service proxying (the 'atproto-proxy' header, pointed at the spindle's did:web service entry), so the user's PDS mints and signs the inter-service auth token; the spindle verifies the token's issuer against their DID document and requires it to match the trigger's 'actor'. Mirrors the sh.tangled.pipeline fields a knot dispatches on a push/PR event. */
const main = /*#__PURE__*/ l.procedure($nsid, $params, $input, $output, [
  'InvalidRequest',
  'Unauthorized',
  'Forbidden',
])

export { main }

export const $lxm = $nsid

type WorkflowResult = {
  $type?: 'com.publicdomainrelay.temp.tangled.spindle.trigger#workflowResult'

  /**
   * Workflow stem that was submitted.
   */
  workflow: string

  /**
   * URL to the log stream for this workflow run.
   */
  logsUrl?: l.UriString

  /**
   * URL to the status stream for this workflow run.
   */
  statusUrl?: l.UriString
}

export type { WorkflowResult }

const workflowResult = /*#__PURE__*/ l.typedObject<WorkflowResult>(
  $nsid,
  'workflowResult',
  /*#__PURE__*/ l.object({
    workflow: /*#__PURE__*/ l.string(),
    logsUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
    statusUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'uri' }),
    ),
  }),
)

export { workflowResult }
