name: 'build: containers'

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Print all files
        run: |
          echo "=== WORKSPACE ==="
          find .
          echo "=== DONE ==="

      - name: Build qemu runner container
        run: |
          set -x
          set +e
          export DEBIAN_FRONTEND=noninteractive
          which findmnt
          sudo apt-get update
          sudo apt-get install -y util-linux
          which findmnt

          sudo findmnt /var/lib/docker
          sudo findmnt /var/lib/containerd

          cd src/typescript/qemu/
          # --push
          sudo docker build --pull --progress plain -f qemu-runner.Dockerfile -t atcr.io/johnandersen777.bsky.social/ccripoc-qemu-runner .
