name: 'build: containers'

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Print all files
        run: |
          find .

      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            qemu:
              - 'src/typescript/qemu/qemu-*'

      - name: Build qemu runner container
        if: steps.changes.outputs.qemu === true
        run: |
          set -x
          set +e

          cd src/typescript/qemu/
          # --push
          sudo docker build --pull --progress plain -f qemu-runner.Dockerfile -t atcr.io/johnandersen777.bsky.social/ccripoc-qemu-runner .
